### ISSUE TITLE
Environment in documentation

### ISSUE THREAD

**Issue by babaorum** [EasyCorp/easy-log-handler#7]
Hi,
In your Readme, you start by talking about changing logs for the dev environment only.
But to achive this, you talk about registering a service for all environment.
Maybe it would be better to install the package in **require-dev** and to register the service in config_dev.yml to avoid loading your package in production, and register a useless service for no use.

And THANK YOU so much ! your library is such a good idea !

**Comment by javiereguiluz** [comment]
@babaorum thanks for raising this concern. You are right. However, instead of solving it the way you propose, I think it may be easier if we just declare the service as `private`.

I did that in 25d508d and it seems to be working: in `dev` this service is inlined and in `prod` it disappears. I'm closing this as "fixed" then. If you don't agree, please reopen. Thanks!
